### ISSUE TITLE
The command '/bin/ash -o pipefail -c chmod a+x /run.sh' returned a non-zero code: 1

### ISSUE THREAD

**Issue by pedroct** [TenySmart/TTLock2MQTT#1]
I'm trying to start the installation, after having configured the repository and store in my Home Assistant installation, but I get this error message:

The command` '/bin/ash -o pipefail -c chmod a+x /run.sh'` returned a non-zero code: 1

My HA installation runs on Docker with OS Debian 11

![image](https://user-images.githubusercontent.com/5846288/205741240-1cae0b77-f214-4cfd-bb67-e4b9a9f76c01.png)

**Comment by DanPatten** [comment]
Here is the fix:

https://github.com/MatterVN/TTLock2MQTT/pull/3
